In [14]:
x = np.zeros((2,3,4),dtype = int)

In [15]:
print(x.shape)

(2, 3, 4)


In [16]:
print(x.shape[1:])

(3, 4)


In [20]:
y = np.zeros(3)
print(y)

print(y.shape)
print(y.shape[1:])

[0. 0. 0.]
(3,)
()


In [24]:
a = np.array(range(10))
print(a[1:])
print(a[:3])
print(a[1:3])

[1 2 3 4 5 6 7 8 9]
[0 1 2]
[1 2]


In [45]:
b = np.array([10,11,12])
c = np.concatenate((a,b))
print(c)

print(x.shape)

new_shape = np.concatenate((np.array([1,9]),x.shape))
print(new_shape)
z = np.zeros(np.concatenate(([1,9],x.shape)))
print(z.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
(2, 3, 4)
[1 9 2 3 4]
(1, 9, 2, 3, 4)


In [49]:
ticks = np.concatenate((40*(np.arange(19)+1),48*np.arange(11)+800))
print(ticks)

[  40   80  120  160  200  240  280  320  360  400  440  480  520  560
  600  640  680  720  760  800  848  896  944  992 1040 1088 1136 1184
 1232 1280]


In [55]:
CorrbyBand = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(CorrbyBand.shape)

Divisor = np.array([[10,100,1000],[1e4,1e5,1e6],[1e7,1e8,1e9]])
print(Divisor.shape)

Quotient = np.divide(CorrbyBand,Divisor)
print(Quotient.shape)
print(Quotient)

(2, 3, 3)
(3, 3)
(2, 3, 3)
[[[1.0e-01 2.0e-02 3.0e-03]
  [4.0e-04 5.0e-05 6.0e-06]
  [7.0e-07 8.0e-08 9.0e-09]]

 [[1.0e+00 1.1e-01 1.2e-02]
  [1.3e-03 1.4e-04 1.5e-05]
  [1.6e-06 1.7e-07 1.8e-08]]]
