In [14]:
x = np.zeros((2,3,4),dtype = int)

In [15]:
print(x.shape)

(2, 3, 4)


In [16]:
print(x.shape[1:])

(3, 4)


In [20]:
y = np.zeros(3)
print(y)

print(y.shape)
print(y.shape[1:])

[0. 0. 0.]
(3,)
()


In [24]:
a = np.array(range(10))
print(a[1:])
print(a[:3])
print(a[1:3])

[1 2 3 4 5 6 7 8 9]
[0 1 2]
[1 2]


In [45]:
b = np.array([10,11,12])
c = np.concatenate((a,b))
print(c)

print(x.shape)

new_shape = np.concatenate((np.array([1,9]),x.shape))
print(new_shape)
z = np.zeros(np.concatenate(([1,9],x.shape)))
print(z.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
(2, 3, 4)
[1 9 2 3 4]
(1, 9, 2, 3, 4)


In [48]:
ticks = np.concatenate((40*(np.arange(19)+1),48*np.arange(11)+800))
print(ticks)

[  40   80  120  160  200  240  280  320  360  400  440  480  520  560
  600  640  680  720  760  800  848  896  944  992 1040 1088 1136 1184
 1232]
